[package]
name = "fib_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
num-bigint = "0.4.5"
num-traits = "0.2.19"

[lib]
name = "fib_rs"
path = "src/fast_doubling_lib.rs"

[[bin]]
name = "fib_rs"
path = "src/fast_doubling_main.rs"
